# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='blocks',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='articles',
            name='dislikes',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='articles',
            name='likes',
            field=models.CharField(max_length=20),
        ),
    ]
