# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 15:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_app', '0002_auto_20180617_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='blocks',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='likes',
        ),
        migrations.AddField(
            model_name='articles',
            name='likes',
            field=models.ManyToManyField(blank='True', related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
