# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 19:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_app', '0003_auto_20180617_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='blocks',
            field=models.ManyToManyField(blank='True', related_name='block', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articles',
            name='dislikes',
            field=models.ManyToManyField(blank='True', related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
