# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 13:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20180618_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='blocks',
            field=models.ManyToManyField(blank='True', related_name='blocks', to=settings.AUTH_USER_MODEL),
        ),
    ]
